# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy Amber

on:
  push:
    branches: [ master, setup-config ]
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  deploy-amber:
    runs-on: ubuntu-latest
    steps:
    - name: install ssh key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.ID_RSA }}
        name: isa_rsa # optional
        known_hosts: ssh-keyscan -H github.com > ~/.ssh/known_hosts
    - name: rsync ssh key
      run: |
        rsync ${HOME}/.ssh/isa_rsa ${{ secrets.HOSTNAME }${HOME}/.ssh/isa_rsa
    - uses: actions/checkout@v2
    - name: setting up python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: copying ssh key
      run: |
        ssh_dir=config/.ssh
        ec2tutkey=config/.ssh/ec2tutkey.pem
        mkdir -p ${ssh_dir}
        touch ${ec2tutkey}
        echo '${{ secrets.EC2TUTKEY }}' > ${ec2tutkey} 
        
        sudo chmod 644 ${ec2tutkey}
        git config pull.ff only
        git pull

        ls -la ${ssh_dir}
    - name: launch application
      run: |
        pwd
        echo ${ssh_dir}
        sudo ssh -i "${ec2tutkey}" ${{ secrets.HOSTNAME }}"
        cd Little-Amber/\n
        forever stopall\n
        git commit -am "${{ secrets.GITHUB_REF }}"\n
        passphrase = ${{ secrets.SSH_PASSPHRASE }}\n
        forever start -c python3 scripts/main.py\n
        "

          
    
