# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploying Amber

on:
  push:
    branches: [ setup-config ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setting up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Configuring AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Copying SSH key
      run: |
        mkdir -p config/.ssh/
        touch config/.ssh/ec2tutkey.pem
        echo '${${{ secrets.EC2TUTKEY }}}' >> config/.ssh/ec2tutkey.pem
        chmod 400 config/.ssh/ec2tutkey.pem
        ls -la
        ssh -i "./config/.ssh/ec2tutkey.pem" ec2-user@ec2-34-216-70-159.us-west-2.compute.amazonaws.com "bash ./launch.sh"
