# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy Amber

on:
  pull_request:
    branches: [ master ]
  jobs:
    deploy-amber:
      runs-on: ubuntu-latest
      steps:
      - name: setup ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_RSA_PUB }}
          name: isa_rsa # optional
          known_hosts: ssh-keyscan -H github.com > ~/.ssh/known_hosts
      - uses: actions/checkout@v2
      - name: setting up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: ssh and launch application
        uses: appleboy/ssh-action@master
        with:
          host: ec2-34-216-70-159.us-west-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.EC2TUTKEY }}
          port: 22
          script: |
            cd Little-Amber/ || return
            pwd
            ls -la
            sudo chmod 644 -r ~/.ssh
            git pull
            bash ./deploy_amber.sh



          
    
