# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploying Amber

on:
  push:
    branches: [ setup-config ]
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  configure-env:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setting up python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: configuring aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
  deploy-application:
    runs-on: ubuntu-latest
    needs: ["configure-env"]
    steps:
    - name: copying ssh key
      id: copy-ssh-key
      run: |
        mkdir -p config/.ssh/
        touch config/.ssh/ec2tutkey.pem
        echo '${${{ secrets.EC2TUTKEY }}}' >> config/.ssh/ec2tutkey.pem
        cat config/.ssh/ec2tutkey.pem
        chmod 400 config/.ssh/ec2tutkey.pem
    - name: automerge
      uses: "pascalgn/automerge-action@v0.14.2"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        PULL_REQUEST: "${{ secrets.GITHUB_REF }}"
    - name: pull and deploy
      run: |
        ls -la ~/.config/
        ssh -i "./config/.ssh/ec2tutkey.pem" ec2-user@ec2-34-216-70-159.us-west-2.compute.amazonaws.com "
        cd Little-Amber/ || return\n
        forever stopall\n
        git commit -am "${{ secrets.GITHUB_REF }}"\n
        passphrase = ${{ secrets.SSH_PASSPHRASE }}
        git pull origin master < cat ${passphrase}\n
        forever start -c python3 scripts/main.py\n
        "

          
    
