# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploying Amber

on:
  push:
    branches: [ setup-config ]
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  launch-application:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setting up python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: configuring aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        mask-aws-account-id: false
    - name: automerge
      uses: "pascalgn/automerge-action@v0.14.2"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        PULL_REQUEST: "${{ secrets.GITHUB_REF }}"
    - name: copying ssh key
      run: |
        ssh_dir=~/.ssh
        mkdir -p ${ssh_dir}
        aws_key=${ssh_dir}/ec2tutkey.pem
        touch ${aws_key}
        echo '${{ secrets.EC2TUTKEY }}' > ${aws_key}   
        
        sudo chmod 600 ${aws_key}
        git pull origin master << yes
    - name: pull application and deploy
      if: success()
      run: |
        ssh_dir=~/.ssh
        aws_key=${ssh_dir}/ec2tutkey.pem
        ls -la ${ssh_dir}
        cat ${ssh_dir}/known_hosts

        ssh -i "${aws_key}" ec2-user@ec2-34-216-70-159.us-west-2.compute.amazonaws.com "
        cd Little-Amber/\n
        forever stopall\n
        git commit -am "${{ secrets.GITHUB_REF }}"\n
        passphrase = ${{ secrets.SSH_PASSPHRASE }}
        git pull > $(cat ${passphrase})\n
        forever start -c python3 scripts/main.py\n
        "

          
    
